# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22ef9190dc64e22fdab8dd646f9c8d057f4944699360d2d0d3d9ef0ee93de27aca5ba123fd806dc68f07d28e830edff7dd4a9d1a67a0c956061e7726e392f92f

test:
  secret_key_base: 69d31be86cd385cf8ece164f7d81d173adb80dafe9df76cedc246f87596f884242a192665f686194d959d049561968677cf09382605014750017a720a2e54d5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
